ALTER TABLE teams
    MODIFY COLUMN kbo_team_code VARCHAR(10) NOT NULL,
    MODIFY COLUMN name VARCHAR(100) NOT NULL,
    MODIFY COLUMN short_name VARCHAR(50) NOT NULL,
    MODIFY COLUMN created_at DATETIME NOT NULL;

ALTER TABLE users
    MODIFY COLUMN email VARCHAR(255) NOT NULL,
    MODIFY COLUMN nickname VARCHAR(100) NOT NULL,
    MODIFY COLUMN provider VARCHAR(50) NOT NULL,
    MODIFY COLUMN point INT NOT NULL,
    MODIFY COLUMN role VARCHAR(50) NOT NULL,
    MODIFY COLUMN status VARCHAR(50) NOT NULL,
    MODIFY COLUMN created_at DATETIME NOT NULL,
    MODIFY COLUMN updated_at DATETIME NOT NULL;

ALTER TABLE games
    MODIFY COLUMN season INT NOT NULL,
    MODIFY COLUMN game_date DATE NOT NULL,
    MODIFY COLUMN home_team_id BIGINT NOT NULL,
    MODIFY COLUMN away_team_id BIGINT NOT NULL,
    MODIFY COLUMN status VARCHAR(50) NOT NULL,
    MODIFY COLUMN created_at DATETIME NOT NULL,
    MODIFY COLUMN updated_at DATETIME NOT NULL;

ALTER TABLE user_predictions
    MODIFY COLUMN user_id BIGINT NOT NULL,
    MODIFY COLUMN game_id BIGINT NOT NULL,
    MODIFY COLUMN point_amount INT NOT NULL,
    MODIFY COLUMN settled TINYINT(1) NOT NULL,
    MODIFY COLUMN created_at DATETIME NOT NULL,
    MODIFY COLUMN updated_at DATETIME NOT NULL;

ALTER TABLE system_predictions
    MODIFY COLUMN game_id BIGINT NOT NULL,
    MODIFY COLUMN home_win_probability DECIMAL(5, 2) NOT NULL,
    MODIFY COLUMN draw_probability DECIMAL(5, 2) NOT NULL,
    MODIFY COLUMN away_win_probability DECIMAL(5, 2) NOT NULL,
    MODIFY COLUMN created_at DATETIME NOT NULL;

ALTER TABLE team_stats
    MODIFY COLUMN team_id BIGINT NOT NULL,
    MODIFY COLUMN season INT NOT NULL,
    MODIFY COLUMN stat_date DATE NOT NULL,
    MODIFY COLUMN collected_at DATETIME NOT NULL;
